# Generated by Django 4.0 on 2022-10-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='primaryproperty',
            table='spb_primary_property',
        ),
    ]
