# Generated by Django 4.0 on 2022-10-19 22:39

import aproperty.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aproperty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название лота')),
                ('slug', models.SlugField(verbose_name='Назваие в url')),
                ('square', models.IntegerField(blank=True, default=None, null=True, verbose_name='Площядть')),
                ('price', models.CharField(help_text='Минимальная цена лота в комплексе', max_length=80, verbose_name='Цена лота')),
                ('addres', models.CharField(max_length=100, verbose_name='Адрес')),
                ('map_script', models.TextField(max_length=500, verbose_name='Скрипт карты')),
                ('description', models.TextField(help_text='Можно использовать html, до 1500 символов', max_length=1500, verbose_name='Полное описание лота')),
                ('title_image', models.ImageField(help_text='Фотография на странице лота', upload_to=aproperty.models.complex_dir_path, verbose_name='Обложка')),
                ('click_amount', models.BigIntegerField(default=0, verbose_name='Кол-во нажатий')),
                ('is_published', models.BooleanField(default=True, help_text='Доступен ли обьект на сайте', verbose_name='Опубликован')),
                ('rooms_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='Кол-во комнат')),
                ('floor', models.IntegerField(blank=True, default=None, null=True, verbose_name='Этаж')),
                ('floor_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='Кол-во этажей в доме')),
                ('decor', models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Ремонт')),
                ('construction_year', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Год постройки')),
                ('bulding_material', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Тип (материал) дома')),
                ('ceiling_height', models.FloatField(blank=True, default=None, null=True, verbose_name='Высота потолков')),
                ('elevators', models.IntegerField(blank=True, default=None, null=True, verbose_name='Пассажирских лифтов')),
                ('freight_elevators', models.IntegerField(blank=True, default=None, null=True, verbose_name='Грузовых лифтов')),
                ('parking', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Парковка')),
                ('ownership', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Форма собственности')),
                ('entrances', models.IntegerField(blank=True, default=None, null=True, verbose_name='Кол во подъездов')),
                ('rooms_on_floor', models.IntegerField(blank=True, default=None, null=True, verbose_name='Квартир на этаже')),
                ('penthouse', models.BooleanField(default=False, verbose_name='Пентхаус')),
                ('terrace', models.BooleanField(default=False, verbose_name='Терраса')),
                ('rooms_in_hous', models.IntegerField(blank=True, default=None, null=True, verbose_name='Квартир в доме')),
                ('window_to', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Окна выходят')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aproperty.area', verbose_name='Район')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aproperty.sitedata', verbose_name='Сайт')),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aproperty.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Втричная недвижимость',
                'verbose_name_plural': 'Втричная недвижимость',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ReImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=aproperty.models.complex_dir_path, verbose_name='Фото')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Описание')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resale.resaleproperty', verbose_name='Обьект недвижимости')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-name'],
            },
        ),
    ]
