# Generated by Django 4.0 on 2022-11-16 08:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0002_resaleproperty_living_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaleproperty',
            name='description',
            field=ckeditor.fields.RichTextField(help_text=' До 2000 символов', max_length=2000, verbose_name='Полное описание лота'),
        ),
    ]
