# Generated by Django 4.0 on 2022-11-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0003_alter_resaleproperty_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resaleproperty',
            name='penthouse',
        ),
        migrations.AlterField(
            model_name='resaleproperty',
            name='decor',
            field=models.CharField(blank=True, choices=[('NO', 'Без ремонта'), ('SIMPLE', 'Косметический'), ('EURO', 'Евроремонт'), ('DESIGN', 'Дизайнерский')], default='NO', max_length=80, verbose_name='Ремонт'),
        ),
    ]
