# Generated by Django 4.0 on 2023-02-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0004_remove_resaleproperty_penthouse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resaleproperty',
            old_name='rooms_in_hous',
            new_name='rooms',
        ),
    ]
