# Generated by Django 4.0 on 2023-02-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0005_rename_rooms_in_hous_resaleproperty_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaleproperty',
            name='decor',
            field=models.CharField(blank=True, choices=[('NO', 'Без отделки'), ('SIMPLE', 'WhiteBox'), ('EURO', 'С отделкой'), ('DESIGN', 'Дизайнерский')], default='EURO', max_length=80, verbose_name='Ремонт'),
        ),
    ]
