# Generated by Django 4.0 on 2023-02-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0006_alter_resaleproperty_decor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resaleproperty',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='resaleproperty',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='longitude'),
        ),
    ]
