# Generated by Django 4.0 on 2022-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aproperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=180, null=True, verbose_name='ФИО'),
        ),
    ]
