version: '3.8'

services:

  big_db:
    container_name: big_db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

networks:
  default:
    name: nginxproxymanager_default
    external: true

volumes:
  postgres_data:
