# Generated by Django 4.0 on 2022-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaleproperty',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='resaleproperty',
            name='window_to',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Окна выходят'),
        ),
    ]
