# Generated by Django 4.0 on 2022-10-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aproperty', '0003_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='complex',
            field=models.CharField(default='avs', max_length=180, verbose_name='Страница'),
            preserve_default=False,
        ),
    ]
