# Generated by Django 4.0 on 2022-09-04 11:48

from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название комплекса')),
                ('slug', models.SlugField(verbose_name='Назваие в url')),
                ('price', models.IntegerField(help_text='Минимальная цена лота в комплексе', verbose_name='Цена лота')),
                ('addres', models.CharField(max_length=100, verbose_name='Адрес')),
                ('district', models.CharField(blank=True, default='', max_length=50, verbose_name='Округ')),
                ('subway', models.CharField(blank=True, default='', max_length=100, verbose_name='Метро')),
                ('map_script', models.TextField(max_length=500, verbose_name='Скрипт карты')),
                ('min_square', models.IntegerField(default=10, verbose_name='Минимальная площядь')),
                ('max_square', models.IntegerField(default=500, verbose_name='Максимальнаяплощядь')),
                ('short_phrase', models.TextField(help_text='Яркая и короткая фраза, отображается на странице комплекса', max_length=250, verbose_name='Короткая фраза')),
                ('description', models.TextField(help_text='Можно использовать html, до 1500 символов', max_length=1500, verbose_name='Полное описание комплекса')),
                ('title_image', models.ImageField(upload_to='', verbose_name='Обложка')),
                ('second_image', models.ImageField(upload_to=property.models.complex_dir_path, verbose_name='Доп. фото')),
                ('logo', models.ImageField(upload_to=property.models.complex_dir_path, verbose_name='Логотип')),
                ('presentation', models.FileField(upload_to='', verbose_name='Презентация комплекса')),
                ('area', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.area')),
                ('click', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.click', verbose_name='Клики')),
                ('images', models.ManyToManyField(to='property.Image', verbose_name='Фотографии комплекса')),
                ('specialist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Новостройка',
                'verbose_name_plural': 'Новостройки',
                'ordering': ['-name'],
            },
        ),
    ]
