# Generated by Django 4.0 on 2022-10-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('primary_property', '0003_alter_primaryproperty_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryproperty',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='property.Image', verbose_name='Фотографии лота'),
        ),
    ]
