# Generated by Django 4.0 on 2022-10-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_client_email'),
        ('primary_property', '0004_alter_primaryproperty_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryproperty',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.area', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='primaryproperty',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.specialist', verbose_name='Специалист'),
        ),
    ]
