# Generated by Django 4.0 on 2022-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_property', '0005_alter_primaryproperty_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryproperty',
            name='max_square',
            field=models.BigIntegerField(default=500, verbose_name='Максимальная площядь'),
        ),
        migrations.AlterField(
            model_name='primaryproperty',
            name='min_square',
            field=models.BigIntegerField(default=10, verbose_name='Минимальная площядь'),
        ),
        migrations.AlterField(
            model_name='primaryproperty',
            name='price',
            field=models.BigIntegerField(help_text='Минимальная цена лота в комплексе', verbose_name='Цена лота'),
        ),
    ]
