# Generated by Django 4.0 on 2022-10-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_property', '0006_alter_primaryproperty_max_square_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryproperty',
            name='price',
            field=models.CharField(help_text='Минимальная цена лота в комплексе', max_length=80, verbose_name='Цена лота'),
        ),
    ]
