# Generated by Django 4.0 on 2022-10-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_property', '0007_alter_primaryproperty_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryproperty',
            name='click',
        ),
        migrations.AddField(
            model_name='primaryproperty',
            name='click_amount',
            field=models.BigIntegerField(default=0, verbose_name='Кол-во нажатий'),
        ),
    ]
