# Generated by Django 4.0 on 2022-10-09 15:25

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_property', '0008_remove_primaryproperty_click_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryproperty',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=property.models.complex_dir_path, verbose_name='Логотип'),
        ),
    ]
