# Generated by Django 4.0 on 2022-10-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_property', '0009_alter_primaryproperty_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryproperty',
            name='lots_number',
            field=models.CharField(blank=True, default='по запросу', max_length=100, verbose_name='Кол-во лотов'),
        ),
    ]
