# Generated by Django 4.0 on 2022-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Роль в проекте')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
