# Generated by Django 4.0 on 2022-10-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Email'),
        ),
    ]
