# Generated by Django 4.0 on 2022-10-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_property', '0008_remove_primaryproperty_click_and_more'),
        ('property', '0003_alter_client_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Click',
        ),
    ]
