# Generated by Django 4.0 on 2022-10-09 12:55

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_delete_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=property.models.complex_dir_path, verbose_name='Фото'),
        ),
    ]
