# Generated by Django 4.0 on 2022-10-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_specialist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Название района'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='role',
            field=models.CharField(max_length=180, verbose_name='Роль в проекте'),
        ),
    ]
