# Generated by Django 4.0 on 2022-11-15 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aproperty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('ltype', models.CharField(choices=[('PRIMARY', 'Первичная недвижимость'), ('RESALE', 'Вторичная недвижимость')], default='PRIMARY', max_length=25, verbose_name='Тип недвижимости')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aproperty.sitedata', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Тип жилья',
                'verbose_name_plural': 'Типы жилья',
            },
        ),
    ]
