# Generated by Django 4.0 on 2022-10-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aproperty', '0002_remove_image_site_alter_sitedata_options'),
        ('primary', '0002_remove_primaryproperty_images_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
