# Generated by Django 4.0 on 2022-11-16 08:48

import aproperty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aproperty', '0002_livingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='logo',
            field=models.FileField(upload_to=aproperty.models.complex_dir_path11, validators=[aproperty.models.validate_logo], verbose_name='Лого'),
        ),
    ]
