# Generated by Django 4.0 on 2022-10-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aproperty', '0003_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedata',
            name='scripts',
            field=models.TextField(max_length=1500, verbose_name='Скрипты аналитики'),
        ),
    ]
