# Generated by Django 4.0 on 2022-10-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_remove_primaryproperty_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryproperty',
            name='main_order',
            field=models.IntegerField(default=0, help_text='Показываются все обьекты с не нулевыми значениями.', verbose_name='Порадок на главной странице'),
        ),
    ]
