# Generated by Django 4.0 on 2022-11-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aproperty', '0001_initial'),
        ('primary', '0002_alter_primaryproperty_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aproperty.sitedata', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Тип жилья',
                'verbose_name_plural': 'Типы жилья',
            },
        ),
        migrations.AddField(
            model_name='primaryproperty',
            name='living_type',
            field=models.ManyToManyField(blank=True, default=None, to='primary.LivingType', verbose_name='Тип жилья'),
        ),
    ]
