# Generated by Django 4.0 on 2022-11-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0003_livingtype_primaryproperty_living_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryproperty',
            name='living_type',
        ),
        migrations.DeleteModel(
            name='LivingType',
        ),
    ]
