# Generated by Django 4.0 on 2022-11-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aproperty', '0002_livingtype'),
        ('primary', '0004_remove_primaryproperty_living_type_delete_livingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryproperty',
            name='living_type',
            field=models.ManyToManyField(blank=True, default=None, to='aproperty.LivingType', verbose_name='Тип жилья'),
        ),
    ]
