# Generated by Django 4.0 on 2022-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0004_alter_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryproperty',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Доступен ли обьект на сайте', verbose_name='Опубликован'),
        ),
    ]
