# Generated by Django 4.0 on 2022-10-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0005_primaryproperty_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='site',
        ),
    ]
