# Generated by Django 4.0 on 2023-02-08 11:23

import aproperty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0007_remove_primaryproperty_logo_primaryproperty_decor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryproperty',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=aproperty.models.complex_dir_path, validators=[aproperty.models.validate_logo], verbose_name='Логотип'),
        ),
    ]
