# Generated by Django 4.0 on 2022-10-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aproperty', '0004_client_complex'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='spb_areas',
        ),
        migrations.AlterModelTable(
            name='areapeculiarity',
            table='spb_areas_peculiarity',
        ),
        migrations.AlterModelTable(
            name='image',
            table='spb_images',
        ),
    ]
